### ISSUE TITLE
[sponsorship_compassion] Improve res_partner view

### ISSUE THREAD

**Issue by ecino** [CompassionCH/compassion-modules#110]
Partner view is not good with buttons in the right corner. We should replace them with v8 style icons:

![partner_moche](https://cloud.githubusercontent.com/assets/8435180/9059803/d89752e6-3aad-11e5-9f9f-960118f4a94d.PNG)

**Comment by ndtran** [comment]
ok -> see pull request #118 
to change icone, change tag using: http://fortawesome.github.io/Font-Awesome/icons/
