### ISSUE TITLE
Image preview not working when editing line

### ISSUE THREAD

**Issue by ecino** [CompassionCH/compassion-modules#137]
When editing a line of a tree view, the widget image preview disappears and shows the image. This results to this in the import letters view :

![image_preview](https://cloud.githubusercontent.com/assets/8435180/11495207/9b6b0d04-9809-11e5-9a4f-7a318585a7e2.PNG)

Would it be feasible to deactivate that behaviour and keep the icon when editing a line ?

**Comment by loikki** [comment]
I think that this issue has been solved

**Comment by ecino** [comment]
@rz-comp what is your fix ? any chance it can be merged into OCA ?
