### ISSUE TITLE
Import lines fields partner_codega and child_code should be references

### ISSUE THREAD

**Issue by ecino** [CompassionCH/compassion-modules#138]
Change fields `partner_codega` and `child_code` to `partner_id` and `child_id` with link to actual records of related models. This makes easier setting the child and the partner in case the qr code detection didn't work.

### Should adapt method `_find_qrcode` :

* https://github.com/CompassionCH/compassion-modules/blob/sbc-devel/sbc_compassion/models/import_letters_history.py#L246

Instead of returning multiple variables, the function could return the dictionary of values needed to be passed to the `create` called at https://github.com/CompassionCH/compassion-modules/blob/sbc-devel/sbc_compassion/models/import_letters_history.py#L254

* https://github.com/CompassionCH/compassion-modules/blob/sbc-devel/sbc_compassion/models/import_letters_history.py#L285

Variable `data` is never used inside the method, but is overidden and returned. Check what is the purpose of this and correct the code by either removing data from the parameters or making use of it. Also add a comment to the function to document the parameters.

**Comment by loikki** [comment]
I need to keep the data parameter because it is used in the creation of a line.
In this function I am turning it in case of a reverse scan
