### ISSUE TITLE
Missing management of gmc_state changes in sds_tracking module

### ISSUE THREAD

**Issue by davidZIVI** [CompassionCH/compassion-modules#75]
gmc_state needs to be merged with sds state to be able to track for example:
- depart of a child 
- a new biennial report needs to sent
- etc...

to do this properly we need to be able to create multiple workflows on a same record a reset a specific one of these workflow (https://www.odoo.com/forum/help-1/question/many-workflows-on-same-record-81693)

**Comment by ecino** [comment]
We keep gmc_state as a separated field and avoid using too many workflows because they are really slow. In future, we will avoid as much as possible using workflows.
